name: Adrian Sampson
author: Adrian Sampson
url: http://adriansampson.net
base: ''
twitter: '@samps'
email: 'asampson@cs.cornell.edu'
logo: https://brand.cornell.edu/images/web-logo.jpg
ghrepo: https://github.com/sampsyo/home

markdown: kramdown
kramdown:
    input: GFM
    hard_wrap: false
    enable_coderay: false
    auto_ids: true
    entity_output: symbolic
    math_engine: null
highlighter: null

exclude:
    - bower_components
    - node_modules
    - package.json
    - bower.json
    - Makefile

permalink: /blog/:title.html

defaults:
    -
        scope:
            path: ""
            type: posts
        values:
            layout: post
    -
        scope:
            path: ""
            type: drafts
        values:
            layout: post

navigation:
    - title: home
      link: /
    - title: research
      link: /research.html
    - title: blog
      link: /blog/
    - title: contact
      link: /contact.html

redirect:
    files/enerjproofs.pdf: media/enerjproofs.pdf

# Rendered drafts.
collections:
    drafts:
        output: true
        permalink: /blog/drafts/:slug.html
